//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Adress_line_1 { get; set; }
        public string Adress_line_2 { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public Nullable<short> Country_ID { get; set; }
        public string Siren { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mail { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
    }
}
